# Monday

In [1]:
fam = ['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
print(fam)

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]


In [2]:
fam2 = [['liz', 1.73], ['emma', 1.68], ['mom', 1.71], ['dad', 1.89]]
print(fam2)

[['liz', 1.73], ['emma', 1.68], ['mom', 1.71], ['dad', 1.89]]


In [4]:
print(fam[0])
fam[0]

liz


'liz'

In [6]:
print(fam2[0])
fam2[0]

['liz', 1.73]


['liz', 1.73]

In [9]:
print(fam2[0][0])
fam2[0][0]

liz


'liz'

In [10]:
print(fam[-1])
print(fam[-2])

1.89
dad


In [11]:
print(fam2[-1])

['dad', 1.89]


In [14]:
print(fam2[-1][-1])
fam2[-1][-2]

1.89


'dad'

In [20]:
print(fam)
print(fam[1:3])
print(fam[1:2])
print(fam[2:2])
print(fam[5:5])

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
[1.73, 'emma']
[1.73]
[]
[]


In [21]:
print(fam2)

[['liz', 1.73], ['emma', 1.68], ['mom', 1.71], ['dad', 1.89]]


In [22]:
print(fam2[0:2])

[['liz', 1.73], ['emma', 1.68]]


In [23]:
print(fam[2:])

['emma', 1.68, 'mom', 1.71, 'dad', 1.89]


In [24]:
print(fam[0:4])

['liz', 1.73, 'emma', 1.68]


In [26]:
print(fam[:])

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]


In [27]:
print(fam[-5:-2])

[1.68, 'mom', 1.71]


# mistake

In [34]:
a = ['a', 'b', 'c', 3, 4, 'd', 6, 7, 8]
print(a)
b = [1,3,7]
print(b)
c = [a[i] for i in b]   
print(c)

['a', 'b', 'c', 3, 4, 'd', 6, 7, 8]
[1, 3, 7]
['b', 3, 7]


In [37]:
fam = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]
print(fam)
second = fam
second[0] = "sister"
print(second)
print(fam)

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
['sister', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
['sister', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]


In [38]:
fam = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]
print(fam)
second = fam.copy()
second[0] = "sister"
print(second)
print(fam)

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
['sister', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]


In [39]:
fam = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]
print(fam)
second = fam[:]
second[0] = "sister"
print(second)
print(fam)

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
['sister', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]


# mistake

In [50]:
fam = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]
print(fam)
fam.append("me")
print(fam)
fam = fam + ["pig",8]
print(fam)

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me']
['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me', 'pig', 8]


In [54]:
fam = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]
print(fam)
fam.insert(4,"joe")
print(fam)
fam.insert(4,['joe', 2.0])
print(fam)

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
['liz', 1.73, 'emma', 1.68, 'joe', 'mom', 1.71, 'dad', 1.89]
['liz', 1.73, 'emma', 1.68, ['joe', 2.0], 'joe', 'mom', 1.71, 'dad', 1.89]


# mistake

In [2]:
fam = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]
print(fam)
# only one item (including strings, numbers, lists) can add in the specify position 
fam.insert(4,["joe",2.0])
print(fam)
# only one item (including a string, a number, a list) can add at the end of the list
fam.append(["joe",2.0])
print(fam)
# can add multiple items (including strings, numbers, lists) at the end of the list, but should be with []
fam.extend([["joe",2.0],3.0,"Joo"])
print(fam)
# can add multiple items (including strings, numbers, lists) in the specify position, but should be with []
fam[2:2] = ["Joo",2.0]
print(fam)

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
['liz', 1.73, 'emma', 1.68, ['joe', 2.0], 'mom', 1.71, 'dad', 1.89]
['liz', 1.73, 'emma', 1.68, ['joe', 2.0], 'mom', 1.71, 'dad', 1.89, ['joe', 2.0]]
['liz', 1.73, 'emma', 1.68, ['joe', 2.0], 'mom', 1.71, 'dad', 1.89, ['joe', 2.0], ['joe', 2.0], 3.0, 'Joo']
['liz', 1.73, 'Joo', 2.0, 'emma', 1.68, ['joe', 2.0], 'mom', 1.71, 'dad', 1.89, ['joe', 2.0], ['joe', 2.0], 3.0, 'Joo']


In [131]:
fam = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]
# only one item can remove from the list
fam.remove(1.73)
print(fam)
# remove the index position
print(fam.pop())
print(fam)
print(fam.pop(2))
print(fam)

['liz', 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
1.89
['liz', 'emma', 1.68, 'mom', 1.71, 'dad']
1.68
['liz', 'emma', 'mom', 1.71, 'dad']


# Wednesday 

In [132]:
import numpy as np

In [133]:
print(np.array([1,2,3]))

[1 2 3]


In [134]:
print(np.array(["joe","koo"]))

['joe' 'koo']


In [136]:
print(np.array([[2.0,"joe","koo"]]))
print(type(np.array([[2.0,"joe","koo"]])))

[['2.0' 'joe' 'koo']]
<class 'numpy.ndarray'>


In [137]:
print(np.array([[1,2,3],[4,5,6]]))

[[1 2 3]
 [4 5 6]]


In [139]:
print(np.ones([2,3,5]))

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [148]:
print(np.full([2,2,3], "Joe"))

[[['Joe' 'Joe' 'Joe']
  ['Joe' 'Joe' 'Joe']]

 [['Joe' 'Joe' 'Joe']
  ['Joe' 'Joe' 'Joe']]]


In [150]:
print(np.full([2,2,3], ["Joe","Loo","Koo"]))

[[['Joe' 'Loo' 'Koo']
  ['Joe' 'Loo' 'Koo']]

 [['Joe' 'Loo' 'Koo']
  ['Joe' 'Loo' 'Koo']]]


In [147]:
print(np.array([[[1,2,3],["Joe","Joe","Joe"]],[[1,2,3],["Joe","Joe","Joe"]]]))

[[['1' '2' '3']
  ['Joe' 'Joe' 'Joe']]

 [['1' '2' '3']
  ['Joe' 'Joe' 'Joe']]]


In [164]:
k = np.arange(1,11,1)
print(k)

print(np.reshape(k,[2,5]))
print(np.reshape(k,[2,5]).ndim)
print(np.reshape(k,[2,5]).shape)
print(np.reshape(k,[2,5]).ndim)
print(np.reshape(k,[2,5]).dtype)

print(np.reshape(k,[2,5]).T)
print(np.reshape(k,[2,5]).T.ndim)
print(np.reshape(k,[2,5]).T.shape)
print(np.reshape(k,[2,5]).ndim)
print(np.reshape(k,[2,5]).dtype)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
(2, 5)
2
int32
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
2
(5, 2)
2
int32


In [177]:
g = np.reshape(k,[2,5])
print(g)
h = g
print(g)
j = h
print(j)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [178]:
print(np.concatenate([g,h,j]))
print(np.concatenate([g,h],axis=0))
print(np.concatenate([g,h],axis=1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]]


In [175]:
print(np.vstack([g,h]))
print(np.hstack([g,h]))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]]


# Friday

In [179]:
print(np.arange(5))

[0 1 2 3 4]


# Quiz

In [5]:
a = ["a","b","c"]
print(a)
a.remove("c")
print(a)

['a', 'b', 'c']
['a', 'b']


In [1]:
import numpy as np
y = np.arange(0,12, 1)
print(y)

# output!!
y.shape # a one dimensional array

[ 0  1  2  3  4  5  6  7  8  9 10 11]


(12,)

In [6]:
print(np.random.randint(0,10,10).reshape([5,2]))

[[5 4]
 [7 2]
 [3 1]
 [3 8]
 [0 6]]
